### ISSUE TITLE
Error while running Windshaft-cartodb in ubuntu

### ISSUE THREAD

**Issue by siva94** [danseely/cartodb-install#3]
I have followed your document and completed the setup
when i run Windshaft-cartodb It's showing the following error

Error: Cannot find module '/home/shiva/Windshaft-cartodb/node_modules/windshaft/node_modules/grainstore/node_modules/millstone/node_modules/srs/lib/binding/node-v0.11.16-linux-ia32/srs_settings.js'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/shiva/Windshaft-cartodb/node_modules/windshaft/node_modules/grainstore/node_modules/millstone/node_modules/srs/lib/srs.js:6:16)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
shiva@ubuntu:~/Windshaft-cartodb$ 

I think I'm missing some dependencies of windshaft but i have no idea any help would be appreciated

**Comment by danseely** [comment]
Sorry, I don't see anything that jumps out. You'd probably be best asking the dev team on the [Google Group](https://groups.google.com/forum/#!forum/cartodb).
